name: "Render Resume"
on:
  push:
    branches:
        - main
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@3.3.0
      with:
        script: |
            just pdf
    - uses: actions/upload-artifact@v3
      with:
        name: Resume-David-Reed.pdf
        path: Resume-David-Reed.pdf